// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace procafeiro.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260820155601_AdicionarAluno")]
    partial class AdicionarAluno
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Dominio.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdAluno");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Cidade");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.HasKey("IdAluno");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("Dominio.Panha", b =>
                {
                    b.Property<int>("IdPanha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdPanha");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("Data");

                    b.Property<int>("Nlitros")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Nlitros");

                    b.Property<int>("Nmedidas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Nmedidas");

                    b.Property<string>("NomeColobarador")
                        .HasColumnType("TEXT")
                        .HasColumnName("NomeColobarador");

                    b.HasKey("IdPanha");

                    b.ToTable("Panhas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
